name: first_week
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  english_words: ^4.0.0
  flutter:
    sdk: flutter

  http: ^0.13.4
  json_annotation: ^4.4.0
  relation: ^3.1.0


dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true
