name: first_week
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  surf_lint_rules: ^1.4.1

flutter:
  uses-material-design: true